### ISSUE TITLE
Language selecting problem

### ISSUE THREAD

**Issue by Lijucay** [Lijukay/Qwotable#11]
**Describe the bug**

Every app restart resets the app to be shown in English...

**To Reproduce**

Steps to reproduce the behavior you encountered:
1. Select language (else than English)
2. Restart app

**Expected behavior**

The app language should be the selected one

**Screenshots**

**Desktop (please complete the following information):**

- App-Version [0.2] (To find this: Open App-Info)

**Smartphone (please complete the following information):**

- Device: [Any]
- OS + OS-Version: [Android 7+] (If you are not sure, you can leave this as it is)

**Additional context**

**Comment by Lijukay** [comment]
Issue must be more precise:

The used language is not English but the Devices language as if the feature is not implemented. However I found out what causes it:

The application does check the locale language, putting it into a SharedPreference and with that, setting the apps language to the devices language. This was unintended and will be fixed on the next update.

**Comment by Lijukay** [comment]
Should be fixed now
