### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Lijucay** [Lijukay/Qwotable#12]
**Describe the feature you'd like to have in detail**

A clear and concise description of what you want to have.

A material you widget that shows quotes periodically.

**Additional context**

**Comment by Lijukay** [comment]
Widget:
Done

Status:
Under testing

**Comment by Lijukay** [comment]
Short information:

You can't select more than one widget and think that they might show different quotes, they do not xD.

The current function to update it periodically is tested. Further information will be available soon.

The layout design on Android phones below Android 12 is yet to be tested. Further information will be available soon.

Dragging another widget to the layout while one is in use causes the widget, that was on the home screen before, to update too. Both widgets always show the same quote.

The widget is only showing quotes as wisdom are too long and I need to learn more about ListViews before I can implement such things

**Comment by Lijukay** [comment]
As for now, the updates do not work. I will try another method

**Comment by Lijukay** [comment]
Okay, unfortunately it seems like I am not able to fix it myself.

**Comment by zoroya1** [comment]
> Okay, unfortunately it seems like I am not able to fix it myself.

May be this can help : 

https://github.com/jameshnsears/QuoteUnquote

I don't have coding knowledge, but this app can do exactly what you are trying to achive

**Comment by Lijukay** [comment]
Good day,

I really thank you for this link. It might really help me ^^

**Comment by Lijukay** [comment]
For myself:

Request of a widget for wisdom (ListView) and a button that refreshes the widget to show, even if the time is not reached, a new quote / wisdom

**Comment by Lijukay** [comment]
So, since I move to Jetpack Compose, I kind of hope that managing widget is a bit easier and not as difficult (or at least it looked difficult) on xml and Java/Kotlin mixed.
