### ISSUE TITLE
Feature Request: Add possibility to add own Qwotable

### ISSUE THREAD

**Issue by Lijucay** [Lijukay/Qwotable#13]
**Describe the feature you'd like to have in detail**

A clear and concise description of what you want to have.

Possibility to add own quotes.
(Saved local on the device)

**Additional context**

**Comment by Lijukay** [comment]
With implementing this, I might change the layout tho it is not necessary.
A bottom navigation view can hold up to 5 items, which, in this case, would be possible.
Recently I started using DrawerLayouts. I am thinking of implementing these.

**Comment by Lijukay** [comment]
I made huge progress in this so I might add it.
As for now, I don't really get how to edit data, so either I will add this feature anyway or I won't and wait until I know this too. I need to think about it once more.

**Comment by Lijukay** [comment]
Edit:

Thanks to a tutorial I finally understand SQLite and am currently working on adding this feature
