### ISSUE TITLE
Feature request : New quotes and inclusion of stoic quotes

### ISSUE THREAD

**Issue by zoroya1** [Lijukay/Qwotable#14]
**Describe the feature you'd like to have in detail**

> i would like to suggest some api's or sites where quotes are available from which Qwotable app can be benefited.

A clear and concise description of what you want to have.

> It will be good if user have one random quote everyday (preferably in widget but i know work i going on) in Qwotable and separate section for stoic quotes for stoic lovers

**Additional context**

Some repos and api i have found :

* Zenquotes API : https://zenquotes.io/

* API for stoic quotes : 
1. https://stoic-quotes.com/api/quote
2. https://api.themotivate365.com/stoic-quote

* other API : https://api.quotable.io

**Comment by Lijukay** [comment]
Heyo,

With the last update, the drawer was added which also made me thought about implementing 3rd party APIs. Now that I have some, I also will try to implement them. Thank you for the request ^^

**Comment by Lijukay** [comment]
Ahh btw, what are stoic quotes? I never heard this word in English

**Comment by zoroya1** [comment]
Stoic is a term which describes the person who practices ideals of stoic philosphy.

Literal meaning of stoic person is a person who is indifferent to emotions whether it is happiness or sadness

 or

 You can say Being stoic is being calm and almost without any emotion. When you're stoic, you don't show what you're feeling and you also accept whatever is happening.

Basically stoicism is a philosophy that was used in ancient greece or rome, there were schools to teach this to people, there are some well renowned teachers of stoicism. Some of them are **Marcus aurelius** (_my personal fav.)_, **Seneca** and **Epictetus** and many more, can't desribe them all in detail here, but Marucs was a One of the most beloved roman king (last true king of roman empire) and seneca was a slave. They all used stoicism in their day to day life and they wrote books and journals (some was for them only though) from which we so called modern people derives wisdom...

Yes, there are four vitues of stoicism : self control, courage, justice and will

Some books i can recommand to read about stoicism is _letter by seneca_ and _Meditations by Marcus aurelius_.

You can find more here : https://en.wikipedia.org/wiki/Stoicism?wprov=sfla1

Yes, i also love anime quotes in Qwotable, looking forward to it <3
maybe famous quote of luffy is not there or i missed it (!?) 
> "Power isn't determined by your size, but size of your heart and dreams"

Let me know if i can be of more help :)

**Comment by Lijukay** [comment]
Hey, thank you for the explanation ^^
I'll try to add these APIs tho I need to learn how to use them, especially since the user can only call these sources limited in a specific period of time.

Also there are a few anime quotes, but currently only from Itachi and a wisdom from Madara. I haven't watched One Piece but I will add this quote to the file as soon as I am finished creating these new issue templates ^^, thank you.

I have a template for requesting Qwotables so if you have time and want to add some of your favourite anime quotes, maybe try to add them there so I can easily add them ^^>

**Comment by zoroya1** [comment]
Thank you for the consideration :)

Sure, i will submit some quotes when i find free time <3

Also, quote of the day will be nice feature [Quotes-status creator](https://github.com/VishnuSanal/Quotes) have daily quotes notification :)

Thank you for great app, especially in Material you theme it looks gorgeous 🎉

**Comment by Lijukay** [comment]
For the other APIs I need to have a look how to implement them. I am currently busy making a website (not from scratch but I want my own style and working on it).

Besides I found another JSON file I will add soon.

**Comment by Lijukay** [comment]
https://github.com/JamesFT/Database-Quotes-JSON


And another JSON file. I will add this one too

**Comment by Lijukay** [comment]
Good Day,

This project is still going on. It will receive updates. Currently I am facing boringness when it comes to Android development. That is why the progress is slowed down. But don't worry. I have no plans to abandon this project in the near future.

**Comment by Lijukay** [comment]
A third party json file has been added to the application and will be included in the next update. However, some changes offered me the possibility to make "daily quotes" much easier. I will replace the home-fragment's "example quotes" with daily quotes, once some changes (thanks to the help of Yanndroid, a very good and cool developer) are finished

**Comment by zoroya1** [comment]
Thanks for head up 😄, happy to see project's smooth development 🎉🥳

**Comment by Lijukay** [comment]
Still on it.
I am sorry that it takes so long but it's the last year of school today so I am somewhat stressed by all the things I have to study ^^
Also I need to finish another app as well

**Comment by zoroya1** [comment]
Don't worry, take your time and take it easy 👍 you got this 🎉 best wishes 💠

**Comment by Lijukay** [comment]
Soo, I found some APIs, that I will use to display random quotes on the home screen of my app.
This is an example:
![Uploading Screenshot_2024-02-06-10-55-14-418_com.lijukay.quotesAltDesign.jpg…]()

**Comment by Lijukay** [comment]
Another update:
Moved this all to Jetpack Compose cuz I like it. This project isn't dead but it takes a huge amount of time since I started my final school year and thus my final exams are moving closer ^^
Also other apps I am working on are taking my time :3

**Comment by zoroya1** [comment]
No worries
:)

**Comment by Lijucay** [comment]
With the last commit to https://github.com/Lijucay/Qwotable/ an API with random stoic quotes and 4 additional APIs were added

**Comment by Lijucay** [comment]
I will close this issue now as the stoic quotes should be added now. The next update will include them.
