### ISSUE TITLE
[Feature request] option to favourite quotes as a heart button besides copy button

### ISSUE THREAD

**Issue by zoroya1** [Lijukay/Qwotable#25]
**Describe the feature you'd like to have in detail**

- Favourite button to favourite the quotes.

A clear and concise description of what you want to have.

Favouriting quotes will make it easier to navigate to favourte quotes.

**Additional context**

**Comment by Lijukay** [comment]
Thank you for the request.

I have planned this as well and I am currently thinking of how to add this ^^

**Comment by Lijukay** [comment]
Just as a little update, I am still working on it. You are not hearing anything from currently because I  have problems with my internet connection.

**Comment by zoroya1** [comment]
No problem, take your time :)
Meanwhile I am enjoying beautiful UI and quotes of qwotable <3

**Comment by Lijukay** [comment]
Quick information:

I am back. Currently, focusing on favourites (when I am programming at Qwotable which is not my focus so progress might be slow)

**Comment by Lijukay** [comment]
Have a look at commit #

**Comment by Lijukay** [comment]
Although this issue has been closed, the discussion will stay open for now. 
The feature will be present in the next update. I am going to inform you then. I just need to add something.

The widget can't be done yet. I have way too much to do currently for learning this too ^^

I am going to continue with the widget at mid-June as I am going right to my exam-phase now.
