### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [Lijukay/Qwotable#38]
See https://f-droid.org/docs/Reproducible_Builds/#aboutlibraries-gradle-plugin.

**Comment by Lijucay** [comment]
Thank you!
When I fixed the issue, should I draft a new release?

**Comment by Lijucay** [comment]
Should be fixed now with [08b6044](https://github.com/Lijucay/Qwotable/commit/08b6044316cd09a00c97365f5013c2a2001ef5e9)

**Comment by linsui** [comment]
A new release or a new apk in old release. :)

**Comment by Lijucay** [comment]
Alright, thank you. I'll add a new APK to the old release and close this issue when I did so. :D

**Comment by Lijucay** [comment]
Added a new APK btw :D

**Comment by linsui** [comment]
Where is the new APK?

**Comment by Lijucay** [comment]
It's in the old release :D

**Comment by linsui** [comment]
Looks like the apk in https://github.com/Lijucay/Qwotable/releases/tag/v12 is not updated and the build still failed...

**Comment by Lijucay** [comment]
Alright. I'll check that out. Perhaps I have uploaded the same build again. Thanks for the information. I'll let you know when I have uploaded the right version then!

**Comment by Lijucay** [comment]
This time, I am sure the file is the correct one

**Comment by linsui** [comment]
It's fixed, thanks!

**Comment by licaon-kter** [comment]
not a RB issue but still fails, https://gitlab.com/fdroid/fdroiddata/-/jobs/7863805725#L829

**Comment by Lijucay** [comment]
I see the issue. I'm confused tho. Any references to BottomNavigationBar should be erased. I'm currently not in a place I can recheck but as soon as I am back home, I will have a quick look

**Comment by Lijucay** [comment]
Apparently I have forgotten to commit the latest changes for the main screen. I'll do that later, when I am back home.

The issue probably is:
import com.lijukay.quotesAltDesign.presentation.composables.BottomNavigationBar
In MainScreen.kt

**Comment by Lijucay** [comment]
I have committed the changes, the build should now not fail anymore

**Comment by licaon-kter** [comment]
@linsui so the next version will fail for sure? https://gitlab.com/fdroid/fdroiddata/-/blob/aac79ad0dbe09e2829cd3ae859f9001736b434ea/metadata/com.lijukay.quotesAltDesign.yml#L62

**Comment by linsui** [comment]
Yes. :)

**Comment by Lijucay** [comment]
Can I mark this issue as resolved?

**Comment by linsui** [comment]
Yes, thanks!
