### ISSUE TITLE
Awesome app^^ - Future feature idea

### ISSUE THREAD

**Issue by MikaelaLovett** [Lijukay/Qwotable#41]
Hii, I love the app, it's perfect for storing Doctor Who quotes that I need to have in multiple notes on Google keep, because they're too long 💗

I was wondering, could you please consider adding settings with the option to copy both the quote, author and source? Because I use it as a quote, which character said it and in which episode was it mentioned and wish to share the info with others too 🙈 Also, option so favourite quotes stay visible after launching the app, pretty please 🥺

Thank you for your hard work and have a lovely day! 🍀

**Comment by Lijucay** [comment]
Hello there. I just now saw your comment. Thanks for the kind words <3
I'm glad you like the app..

As for the feature requests, I will add them to my project's todo list and hopefully get them done soon. 🤞🍀

**Comment by MikaelaLovett** [comment]
> Hello there. I just now saw your comment. Thanks for the kind words <3
> I'm glad you like the app..
> 
> As for the feature requests, I will add them to my project's todo list and hopefully get them done soon. 🤞🍀

Aww you're welcome and thank you too! I'm excited to see what will future updates bring! 💗

**Comment by Lijucay** [comment]
![Screenshot_2024-09-12-01-06-25-000_com.lijukay.quotesAltDesign.jpg](https://github.com/user-attachments/assets/f971277f-1b26-4946-9058-dd8fafa49f00)

This will be available with the next update, giving you full control over what information you want to share (good for these guessing games)

**Comment by MikaelaLovett** [comment]
> )

Aww thank you so much, that's so cool!! 🥺💗 I really appreciate it!

**Comment by Lijucay** [comment]
> Edit: I hope it's not too much to inquire about (again, I'm sorry!), you've already made it the best quotes app out there 🙈, but I just had one more idea, tho I'm not sure how difficult it'd be to implement? Would you also please consider adding sorting options for the quotes in the future? (Either by authors in alphabetical order, the quotes, the episodes/source, custom etc.) Or maybe even a search function? (Possibly a backup - export/import) Both could compliment the sharing feature well imho. Of course, only if it's something you think others would like to use too 🙈💗

Oh yes. I've been planning a sorting feature and a search feature for a while now but I haven't been able to implement it yet (tho it shouldn't be too difficult to do so) :3

Searching feature can be an option if I get it to work properly. 

Also, I am planning to add an export/import feature for your own quotes and might even be able to implement it for the next update.

**Comment by MikaelaLovett** [comment]
> > Edit: I hope it's not too much to inquire about (again, I'm sorry!), you've already made it the best quotes app out there 🙈, but I just had one more idea, tho I'm not sure how difficult it'd be to implement? Would you also please consider adding sorting options for the quotes in the future? (Either by authors in alphabetical order, the quotes, the episodes/source, custom etc.) Or maybe even a search function? (Possibly a backup - export/import) Both could compliment the sharing feature well imho. Of course, only if it's something you think others would like to use too 🙈💗
> 
> Oh yes. I've been planning a sorting feature and a search feature for a while now but I haven't been able to implement it yet (tho it shouldn't be too difficult to do so) :3
> 
> Searching feature can be an option if I get it to work properly. 
> 
> Also, I am planning to add an export/import feature for your own quotes and might even be able to implement it for the next update.
> 
> 

Aww thank you so much for considering everything, no matter when (or if) the updates come, I'm really excited! 👀💗

**Comment by MikaelaLovett** [comment]
Thank you for the release!! 👀💗

**Comment by Lijucay** [comment]
No problem. I won't close the issue at the moment for there are other suggestions from you that I have not yet added to my to-do list. When I'm done working today, I might add them.

Have fun :D

**Comment by Lijucay** [comment]
Added everything to my to-do list. I'll close the issue now
