### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Lijucay** [Lijukay/Qwotable#7]
**Describe the bug**

French language is not supported and causes some issues.
For example it does lead to an empty quote and wisdom page as the URL with fr does not exist or the language preference summary is set to the English one as no translation for french is existing 

**To Reproduce**

Steps to reproduce the behavior you encountered:
1. Go to Settings 
2. Click on language
3. Click on French and then on okay
4. See the issues

**Expected behavior**

French language shown up and French quotes and wisdom are getting parsed

**Screenshots**

No screenshots

**Desktop (please complete the following information):**

- App-Version [e.g. 22] (To find this: Open Settings, scroll to the end. There is a text)

0.1.6 beta

**Smartphone (please complete the following information):**

- Device: [e.g. Samsung Galaxy A50] Samsung Galaxy A50, Galaxy Tab S6 lite (and else)
- OS + OS-Version: [e.g. OneUI 5] (If you are not sure, you can leave this as it is)

OneUI 4.1.1 and else

**Additional context**

None

**Comment by Lijukay** [comment]
Fixed at 0.1.7rc
