### ISSUE TITLE
Not supported languages

### ISSUE THREAD

**Issue by Lijucay** [Lijukay/Qwotable#9]
**Describe the bug**

When the system uses a language, that is not officially supported by the app, following things happen:
1. The qwotable are not getting parsed
2. The settings-language-dialog does not show english as selected

**To Reproduce**

Steps to reproduce the behavior you encountered:
1. Use a not supported language (such as dansk)
2. Open Qwotable (for the first time ofc)

**Expected behavior**

Qwotable should be in English (and it is) and should parse English Qwotable

**Screenshots**

**Desktop (please complete the following information):**

- App-Version [e.g. 22] (To find this: Open App-Info)

**Smartphone (please complete the following information):**

- Device: [Any]
- OS + OS-Version: [Any]

**Additional context**

**Comment by Lijukay** [comment]
Closed:
The issue was fixed. Now, Qwotable will check the system language. If it is neither "en" nor "fr" nor "de", the language is set to "en" (because it is the language, most people are talking)
